variable "name" {}
variable "engine" {}
variable "engine_version" {}
variable "instances" {}
variable "vpc_id" {}
variable "subnets" {}
variable "allowed_cidr_blocks" {}
variable "default_database_name" {}
variable "master_username" {}
variable "master_password" {}
